export let envRP = {
  offlineSeats: 'http://41.223.55.14:7025',
  searchflow: 'https://flightsearch.flytoall.com',
  searchflowAi: 'https://automation.round-pixel.net',
  BookingFlow: 'https://flightflow.flytoall.com',
  // BookingFlow: 'https://flightflow.round-pixel.net',
  FareRules: 'https://flightprov.round-pixel.net',
  asm: 'https://backofficeapi.round-pixel.net',
  Apihotels: 'https://hotelsapi.round-pixel.net',
  users: 'https://flightsearch.flytoall.com',
  // users: 'https://Usersapi.flytoall.com',
  // users: 'https://usersapi.round-pixel.net',
  // admin: 'https://adminapi.round-pixel.net',
  admin: 'https://adminapi.flytoall.com',
  getDPayment: 'https://adminapi.round-pixel.net/',
  bookHotels: 'https://hotels.round-pixel.net',
  prepay: 'https://prepayapi.round-pixel.net',
  backOffice: 'https://backofficeapi.round-pixel.net',
  FlightTop: 'https://flightsearch.round-pixel.net',
  staticPages: 'https://stagingcms.round-pixel.net',
  offers: {
    getAll: 'http://41.215.243.36:7893/api/GetAllOffersAPI?POS=',
    getByID: 'http://41.215.243.36:7893/api/GetOfferByIdAPI?OfferId=',
    BookOffer: 'http://41.215.243.36:7895/api/BookOffer',
    RetriveItineraryDetails: '/api/Admin/RetriveItineraryDetails',
  },
};
